#!/bin/sh

# Using a 'cat' here document, create a file for jekyll
# website containing what's required for pages.

# You call the script without parameters
#   ./createpage

DIR="pages/"

echo "Section? "
read section
# Convert to lowercase
section=$(echo $section | tr '[:upper:]' '[:lower:]')
DIR+=$section

echo "Name? "
read name
# Convert to lowercase
name=$(echo $name | tr '[:upper:]' '[:lower:]')

# Uppercase first letter
Section="$(tr '[:lower:]' '[:upper:]' <<< ${section:0:1})${section:1}"
Name="$(tr '[:lower:]' '[:upper:]' <<< ${name:0:1})${name:1}"

echo "Do you want a short section name? (y/n) "
read answer
case ${answer:0:1} in
    y|Y )
        echo "Short section name? "
        read sec_short
        # Convert to lowercase
        sec_short=$(echo $sec_short | tr '[:upper:]' '[:lower:]')
    ;;
    * )
        sec_short=$section
    ;;
esac

if [ ! -d "${DIR}" ]; then
    mkdir $DIR
fi

touch ${DIR}/${sec_short}_${name}.md

cat <<EOF >"${DIR}/${sec_short}_${name}.md"
---
title: ${Section} / ${Name}
tags: [${sec_short}, ${name}]
keywords: ${section}, ${name}
sidebar: wiki_sidebar
permalink: ${sec_short}_${name}.html
---

EOF

# Add tags
for tag in $sec_short $name; do
    if ! egrep -q "^\s\s- $tag" _data/tags.yml; then
        bash createtag $tag
    fi
done

exit
